name: Check contributor packs
on:
  schedule:
    # runs at minute 0 of the 0th and 0th hour every day.
    - cron:  '0 0 * * *'
jobs:
  handle_contributor_stale_branches:
    runs-on: ubuntu-latest
    if: github.repository == 'demisto/content'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      - name: Sync Base Branch to Master
        env:
          CONTENTBOT_GH_ADMIN_TOKEN: ${{ secrets.CONTENTBOT_GH_ADMIN_TOKEN }}
        run: |
          echo "Handling stale contribution base branches (contrib/*)"
          cd Utils/github_workflow_scripts
          pipenv install --dev
          pipenv run ./close_stale_contrib_branches.py
          echo "Finished deleting stale branches"
